#ifndef FEEDBACKPROCESSOR_H
#define FEEDBACKPROCESSOR_H

#include "Std_Types.h"

#define FEEDBACKPROCESSOR_SW_MAJOR_VERSION 1
#define FEEDBACKPROCESSOR_SW_MINOR_VERSION 0
#define FEEDBACKPROCESSOR_SW_PATCH_VERSION 0

#define FB_MAP_SIZE 8

FUNC(Std_ReturnType, FEEDBACKPROCESSOR_CODE) FeedbackProcessor_Init(void);
FUNC(Std_ReturnType, FEEDBACKPROCESSOR_CODE) FeedbackProcessor_Update(uint16 adc_val);
FUNC(Std_ReturnType, FEEDBACKPROCESSOR_CODE) FeedbackProcessor_Get(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) pos);

#endif /* FEEDBACKPROCESSOR_H */
