#ifdef COMMANDPARSER_START_SEC_CODE
#undef COMMANDPARSER_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef COMMANDPARSER_STOP_SEC_CODE
#undef COMMANDPARSER_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
