#ifdef FEEDBACKPROCESSOR_START_SEC_CODE
#undef FEEDBACKPROCESSOR_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef FEEDBACKPROCESSOR_STOP_SEC_CODE
#undef FEEDBACKPROCESSOR_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
