#ifndef FEEDBACK_PROCESSOR_MEMMAP_H
#define FEEDBACK_PROCESSOR_MEMMAP_H

#define FEEDBACK_PROCESSOR_START_SEC_CODE
#include "MemMap.h"

#define FEEDBACK_PROCESSOR_STOP_SEC_CODE
#include "MemMap.h"

#endif /* FEEDBACK_PROCESSOR_MEMMAP_H */
