#ifndef FEEDBACKPROCESSOR_MEMMAP_H
#define FEEDBACKPROCESSOR_MEMMAP_H

/* Memory mapping macros for FeedbackProcessor */

#define FEEDBACKPROCESSOR_START_SEC_CODE
#define FEEDBACKPROCESSOR_STOP_SEC_CODE

#define FEEDBACKPROCESSOR_START_SEC_CONST_16
#define FEEDBACKPROCESSOR_STOP_SEC_CONST_16

#define FEEDBACKPROCESSOR_START_SEC_CONST_8
#define FEEDBACKPROCESSOR_STOP_SEC_CONST_8

#define FEEDBACKPROCESSOR_START_SEC_VAR_INIT_UNSPECIFIED
#define FEEDBACKPROCESSOR_STOP_SEC_VAR_INIT_UNSPECIFIED

#endif /* FEEDBACKPROCESSOR_MEMMAP_H */
