#ifndef LEDSTATUS_MEMMAP_H
#define LEDSTATUS_MEMMAP_H

/* Memory mapping macros for LedStatus */

#define LEDSTATUS_START_SEC_CODE
#define LEDSTATUS_STOP_SEC_CODE

#define LEDSTATUS_START_SEC_VAR_INIT_UNSPECIFIED
#define LEDSTATUS_STOP_SEC_VAR_INIT_UNSPECIFIED

#endif /* LEDSTATUS_MEMMAP_H */
